springdoc:
  version: 2
  swagger-ui:
    path: /swagger-ui
spring:
  liquibase:
    change-log: "classpath:/db/changelog.xml"
  datasource:
    url: "jdbc:postgresql://localhost:5433/pdapp_db"
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
